# Generated by Django 4.0.4 on 2022-09-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataStorage', '0002_users_delete_customer_delete_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.BigIntegerField(unique=True)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('from_location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ticket_price', models.IntegerField()),
            ],
        ),
    ]
