# Generated by Django 4.0.4 on 2022-09-02 12:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataStorage', '0003_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.BigIntegerField(unique=True)),
                ('booking_date', models.DateTimeField(default=datetime.datetime(2022, 9, 2, 18, 6, 39, 404184))),
                ('total_passengers', models.IntegerField()),
                ('total_price', models.BigIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataStorage.vehicle')),
            ],
        ),
    ]
