# Generated by Django 4.0.4 on 2022-09-04 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataStorage', '0012_otp_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 11, 32, 42, 178449)),
        ),
    ]
