# Generated by Django 4.0.4 on 2022-10-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataStorage', '0016_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='onboarding_date',
            field=models.DateField(null=True),
        ),
    ]
