# Generated by Django 4.0.4 on 2022-11-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataStorage', '0017_booking_onboarding_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('payment_id', models.CharField(max_length=50, null=True, unique=True)),
                ('payment_amount', models.IntegerField()),
                ('receipt', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataStorage.booking')),
            ],
        ),
    ]
