# Generated by Django 4.0.4 on 2022-11-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataStorage', '0018_paymentsstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsstatus',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
